language: bash
sudo: true
dist: trusty

env:
  - EOS_BRANCH=v1.4.1 PYTHON_VERSION=3.5.6 EOSFACTORY_BRANCH=master

script:
  - docker build -t e2e --build-arg eos_branch=${EOS_BRANCH} --build-arg eosfactory_branch=${EOSFACTORY_BRANCH} --build-arg RamPayerExchange_branch=${TRAVIS_PULL_REQUEST_BRANCH} --build-arg python_version=${PYTHON_VERSION} ./tests/integration/
  - docker run -ti e2e "python /opt/RamPayerExchange/tests/local_test.py"
